-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fb

local flatbuffers = require('flatbuffers')

local unitconfigTR = {} -- the module
local unitconfigTR_mt = {} -- the class metatable

function unitconfigTR.New()
    local o = {}
    setmetatable(o, {__index = unitconfigTR_mt})
    return o
end
function unitconfigTR.GetRootAsunitconfigTR(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = unitconfigTR.New()
    o:Init(buf, n + offset)
    return o
end
function unitconfigTR_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function unitconfigTR_mt:_id()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function unitconfigTR_mt:Name()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function unitconfigTR_mt:Desc()
    local o = self.view:Offset(8)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function unitconfigTR_mt:Position()
    local o = self.view:Offset(10)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function unitconfigTR_mt:Height()
    local o = self.view:Offset(12)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function unitconfigTR_mt:Weight()
    local o = self.view:Offset(14)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Int32, o + self.view.pos)
    end
    return 0
end
function unitconfigTR.Start(builder) builder:StartObject(6) end
function unitconfigTR.Add_id(builder, Id) builder:PrependInt32Slot(0, Id, 0) end
function unitconfigTR.AddName(builder, name) builder:PrependUOffsetTRelativeSlot(1, name, 0) end
function unitconfigTR.AddDesc(builder, desc) builder:PrependUOffsetTRelativeSlot(2, desc, 0) end
function unitconfigTR.AddPosition(builder, position) builder:PrependInt32Slot(3, position, 0) end
function unitconfigTR.AddHeight(builder, height) builder:PrependInt32Slot(4, height, 0) end
function unitconfigTR.AddWeight(builder, weight) builder:PrependInt32Slot(5, weight, 0) end
function unitconfigTR.End(builder) return builder:EndObject() end

return unitconfigTR -- return the module