-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: fb

local flatbuffers = require('flatbuffers')

local unitconfigTB = {} -- the module
local unitconfigTB_mt = {} -- the class metatable

function unitconfigTB.New()
    local o = {}
    setmetatable(o, {__index = unitconfigTB_mt})
    return o
end
function unitconfigTB.GetRootAsunitconfigTB(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = unitconfigTB.New()
    o:Init(buf, n + offset)
    return o
end
function unitconfigTB_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function unitconfigTB_mt:UnitconfigTRS(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('fb.unitconfigTR').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function unitconfigTB_mt:UnitconfigTRSLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function unitconfigTB.Start(builder) builder:StartObject(1) end
function unitconfigTB.AddUnitconfigTRS(builder, unitconfigTRS) builder:PrependUOffsetTRelativeSlot(0, unitconfigTRS, 0) end
function unitconfigTB.StartUnitconfigTRSVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function unitconfigTB.End(builder) return builder:EndObject() end

return unitconfigTB -- return the module