--Generated By msgid-gen-lua Do not Edit
local config = {
	[10001] = "login.req_login",
	[10002] = "login.rsp_login",
	[11001] = "login.ntf_logout",
	[30001] = "user.req_create_user",
	[30002] = "user.rsp_create_user",
	[30003] = "user.req_change_name",
	[30004] = "user.rsp_change_name",
	[30001] = "room.req_join_match",
	[30002] = "room.rsp_join_match",
	[30003] = "room.req_cancel_join_match",
	[30004] = "room.rsp_cancel_join_match",
	[31001] = "room.ntf_join_match_result",
	[31002] = "room.ntf_join_match_mateinfo",
}
return config
