--Generated By msgid-gen-lua Do not Edit
local config = {
	[9001] = "common.heart_beat",
	[1001] = "login.req_login",
	[1002] = "login.rsp_login",
	[1101] = "login.ntf_logout",
	[3001] = "user.req_create_user",
	[3002] = "user.rsp_create_user",
	[3003] = "user.req_change_name",
	[3004] = "user.rsp_change_name",
	[3001] = "room.req_join_match",
	[3002] = "room.rsp_join_match",
	[3003] = "room.req_cancel_join_match",
	[3004] = "room.rsp_cancel_join_match",
	[3101] = "room.ntf_join_match_result",
	[3102] = "room.ntf_join_match_mateinfo",
}
return config
